Intel compiler complains if inttypes.h from C std library is used.
This change solves the compiler error:

    SIRIUS/src/runtime.h(214): error: expected a ")"
      printf("hash(%s): %" PRIx64 "\n", label__.c_str(), hash__);

Effects for other compilers should be checked.